#!/bin/sh
exec /home/tatsumi/perl5/perlbrew/perls/perl-5.16.1/bin/start_server --port=8002 --interval=10 -- /home/tatsumi/perl5/perlbrew/perls/perl-5.16.1/bin/plackup -s Starman -MFindBin -a /home/tatsumi/mojohel/mojo_hel_web.psgi
